apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: shestera
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "20Mi"